# Generated by Django 5.1.1 on 2024-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_1', models.CharField(max_length=100)),
                ('product_name_2', models.CharField(max_length=100)),
                ('product_name_3', models.CharField(max_length=100)),
                ('price_1', models.IntegerField()),
                ('price_2', models.IntegerField()),
                ('price_3', models.IntegerField()),
                ('product_description_1', models.TextField(max_length=255)),
                ('product_description_2', models.TextField(max_length=255)),
                ('product_description_3', models.TextField(max_length=255)),
                ('available_qty_1', models.IntegerField()),
                ('available_qty_2', models.IntegerField()),
                ('available_qty_3', models.IntegerField()),
            ],
        ),
    ]
