# Generated by Django 5.1.1 on 2024-09-11 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='available_qty_1',
            new_name='available_qty',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='price_1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='product_description_1',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='product_name_1',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='available_qty_2',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='available_qty_3',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='product_description_2',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='product_description_3',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='product_name_2',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='product_name_3',
        ),
        migrations.AlterField(
            model_name='productentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
