# Generated by Django 5.1.1 on 2024-10-09 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('npm', models.IntegerField()),
                ('kelas', models.CharField(max_length=1)),
            ],
        ),
    ]
